make prefix dynamic and configurable
the-programmers-hangout/Chronos pull request #36
Opened 2020-10-03 17:45 UTC by codevenkat

This PR fixes #30

2020-10-03 17:54 UTC, codevenkat commented
Hmm `Array.find(...)` might've been a cleaner solution? Or is this fine?

2020-10-04 02:34 UTC, ridays2001 approved these changes
Found a mistake. Rest all looks fine to me 👍🏻

2020-10-04 04:09 UTC, ridays2001 requested changes
If there is no saved prefix for the server, the bot won't have a default prefix. Return a default prefix '+' if there are no saved prefixes.

2020-10-04 04:09 UTC, ridays2001 commented on src/index.js
> +        return prefix;
This can be changed to `return prefix || '+';`

2020-10-04 07:24 UTC, ridays2001 approved these changes
Okie. Should work now, I guess 👍🏻

2020-10-04 07:31 UTC, DracTheDino requested changes, later dismissed
It’d be nice if `configFile` could be changed to just `config` to remain consistent with other files in the project. Other than that, I don’t see any issue on first glance. I’ll get on my PC soon and will test it.

2020-10-04 07:41 UTC, codevenkat commented
@DracTheDino there was a `config();` function in the index.js file from `require('dotenv')`, which is why I didn't name it that

2020-10-04 07:42 UTC, DracTheDino commented
> @DracTheDino there was a `config();` function in the index.js file from `require('dotenv')`, which is why I didn't name it that

Okay then, no problem. I’ll dismiss the review and then test it out on my PC. If all’s good I’ll merge it 👍

2020-10-04 10:52 UTC, closed without merging